### PR TITLE
VM steal time measurement

### PR DESCRIPTION
**Pull request by phsm**
Hello, 

I've implemented VM steal time metrics. 
Technically it is "the time the CPU thread spent in the scheduler queue". However, it equals to the VM %steal on my tests.

However, it does a little work behind libvirt's back:
- It leverages "query-cpus" qemu-monitor-command in order to get PIDs of the CPU threads. Unfortunately this call requires read-write libvirt access
- it reads /proc/<thread_pid>/schedstat directly.

Please let me know in case you have any suggestions regarding the PR.

### CODE REVIEW

**Comment by rumanzo** [comment]
Hi! You did great work, but if change readonly access you need to do add logic to provide login/password, may be some checks that login password really needed. 
For example, an oVirt installation define own credentials to libvirt

**Comment by phsm** [comment]
maybe it would be wise in this case to hide this functionality on behind an additional cmdline argument?

I.e. 
```go
if enableStealTimeCollecting {
    conn, err = libvirt.NewConnect(uri)
} else {
    conn, err = libvirt.NewConnectReadOnly(uri)
}
```

**Comment by rumanzo** [comment]
It's noot look good.
Look an old commit https://github.com/rumanzo/libvirt_exporter_improved/commit/daf67eb5b6881816cd8ba20497a86f8eabbc3973#diff-37c75acf358c3b259588c401b5ee97f8L360-L379 
the algorithm should be like this:
Enable StealTimeCollecting if:
a.) login and password provided
b.) auth not needed (check err after connect)
else disable StealTimeCollecting and use NewConnectReadOnly , it's safe

**Comment by phsm** [comment]
Gotcha, 
Seems doable, will work on it.

**Comment by phsm** [comment]
Updated the PR with some adjustments:
1. Now it tries the authentication as suggested: First try without auth, if it gives an error, then tries to authenticate with SASL. Then as the last resort it tries ReadOnly session without authentication (and disables steal time accounting)

2. Reworked couple of functions to be methods of LibvirtExporter object. That will reduce passing arguments through multiple functions.

3. Added two more command line flags: libvirt.auth.username and libvirt.auth.password. They also can be set up as an environmental variabes (if you dont want the password to be shown in the process list).  By default both username and password are empty string, thus the authentication attempt is skipped in this case.


Tested on my ubuntu20.04 stand:
1. Read-write access without authentication
2. Read-write access with authentication

**Pull request merged**
